version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: echo npm version
          command: 'npm -v'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: test1.js lint check
          command: eslint test1.js
      - run:
          name: test2.js lint check
          command: eslint test2.js